app/Http/routes.php
<?php
use App\Models\Zone;
use App\Models\Category;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Route::get('/', 'WelcomeController@index');
// 
// Route::get('home', 'HomeController@index');
// 
// Route::controllers([
// 	'auth' => 'Auth\AuthController',
// 	'password' => 'Auth\PasswordController',
// ]);

Route::group(['before' => 'shieldsquare'], function(){



Route::any('api/white', 'HomeController@apiRedirectHack');
Route::any('api/call_logs/create', array('uses'=>'Administration\Call_logsController@logCall'));

Route::any('api/call_logs/test', array('uses'=>'Administration\Call_logsController@testSMS'));




Route::filter('manage_highlights', function()
{
  if (! Entrust::can('manage_highlights') ) // Checks the current user
  {
    return Redirect::to('/admin');
  }
});
Route::filter('manage_zones', function()
{
  if (! Entrust::can('manage_zones') ) // Checks the current user
  {
    return Redirect::to('/admin');
  }
});

Route::filter('manage_users', function()
{
  if (! Entrust::can('manage_users') ) // Checks the current user
  {
    return Redirect::to('/admin');
  }
});
Route::filter('manage_categories', function()
{
  if (! Entrust::can('manage_categories') ) // Checks the current user
  {
    return Redirect::to('/admin');
  }
});

Route::when('admin/zones*', 'manage_zones');
Route::when('admin/highlights*', 'manage_highlights');
Route::when('admin/accounts*', 'manage_users');
Route::when('admin/categories*', 'manage_categories');

Route::get('jobs', ['before' => 'mazkara.cache', 'after' => 'mazkara.cache', 'uses'=>'HomeController@jobs']);
Route::get('jobs/{id}', ['before' => 'mazkara.cache', 'after' => 'mazkara.cache', 'uses'=>'HomeController@showJob']);
Route::get('about', ['before' => 'mazkara.cache', 'after' => 'mazkara.cache', 'uses'=>'HomeController@about']);
Route::get('contact', ['before' => 'mazkara.cache', 'after' => 'mazkara.cache', 'uses'=>'HomeController@contact']);
Route::post('contact', ['before' => 'mazkara.cache', 'after' => 'mazkara.cache', 'uses'=>'HomeController@postContact']);
Route::get('culture', ['uses'=>'HomeController@culture']);

$locale = Request::segment(1);

if (!Cache::has(mzk_cache_name('zones.cities.slug.list'))){
  $expiresAt = \Carbon\Carbon::now()->addMinutes(18000);
  Cache::add(mzk_cache_name('zones.cities.slug.list'), Zone::cities()->get()->lists('slug', 'id')->all(), $expiresAt);
}

if (!Cache::has(mzk_cache_name('zones.subzones.slug.list'))){
  $expiresAt = \Carbon\Carbon::now()->addMinutes(18000);
  Cache::add(mzk_cache_name('zones.subzones.slug.list'), Zone::notCities()->get()->lists('slug', 'id')->all(), $expiresAt);
}

Route::pattern('city', '[a-z0-9-]+');
Route::pattern('subzone', '[a-z0-9-]+');

Route::bind('city', function($value, $route) {  
  $locales = Cache::get(mzk_cache_name('zones.cities.slug.list'));

  if($zid = array_search($value, $locales)){
    return $zid;
  }
  App::abort(404);
});

Route::bind('subzone', function($value, $route) {  
  $locales = Cache::get(mzk_cache_name('zones.subzones.slug.list'));

  if($zid = array_search($value, $locales)){
    return $zid;
  }
  App::abort(404);
});


//Cache::get('zones.cities.list');
//if(in_array($locale, MazkaraHelper::getCitiesSlugList())):
  //Route::get('{city}', 'BusinessesController@listByCity');
  //Route::get('{city}/beauty-and-wellness-centers', 'BusinessesController@listByCity');
  //Route::get('{city}/{subzone}-beauty-and-wellness-centers', 'BusinessesController@listByCityAndZone');
  //Route::get('{city}/{slug}', ['as'=>'businesses.view.by.slug', 'uses'=> 'BusinessesController@slug']);
  //Route::get('{city}/{slug}', ['as'=>'businesses.view', 'uses'=> 'BusinessesController@slug']);
  //Route::get('find/{category-slug}', ['as'=>'businesses.search.by.category', 'uses'=> 'BusinessesController@category']);
//endif;

Route::group(['before' => ''], function(){


Route::group(array('before' => 'mazkara.cache', 'after' => 'mazkara.cache'), function(){
  //remember(1800, 'city.route.listings')
  $cities = mzk_cities_as_associative_from_json('id', 'slug');

  foreach($cities as $city_id => $city):
  //  Route::get($city, [ 'as'=>'businesses.list.by.city.for.'.$city, 
  //                      'uses'=>'BusinessesController@listByCity']);



    Route::get($city, [ 'as'=>'businesses.list.by.city.for.'.$city, 
                        'uses'=>'HomeController@index']);
    Route::get($city.'/beauty-and-wellness-centers/{services?}',                      
                      function() use($city){
                        return Redirect::to(route('businesses.list.by.city.append.for.'.$city));
                      });

    Route::get($city.'/salons-spas-and-fitness/{services?}', 
                      function() use($city){
                        return Redirect::to(route('businesses.list.by.city.append.for.'.$city));
                      });

    Route::get($city.'/salons-and-spas/{services?}', 
                      ['as'=>'businesses.list.by.city.append.for.'.$city, 
                        'uses'=>'BusinessesController@listByCity']);

    Route::get($city.'/{subzone}-beauty-and-wellness-centers/{services?}', 
                      function() use($city){
                        return Redirect::to(route('businesses.list.by.city.and.zone.for.'.$city));
                      });

    Route::get($city.'/{subzone}-salons-spas-and-fitness/{services?}', 
                      function() use($city){
                        return Redirect::to(route('businesses.list.by.city.and.zone.for.'.$city));
                      });
    Route::get($city.'/{subzone}-salons-and-spas/{services?}', 
                      ['as'=>'businesses.list.by.city.and.zone.for.'.$city, 
                        'uses'=>'BusinessesController@listByCityAndZone']);
    //remember(1800, 'category.route.listings')
    $categories = mzk_categories_as_associative_from_json('id', 'slug');
    $categories = array_reverse($categories);
    foreach($categories as $category_id=>$category_slug):
      
      $name = 'businesses.list.category.'.$category_slug.'.by.city.append.for.'.$city;
      Route::get($city.'/'.(str_plural($category_slug)), 
                  ['as'=>$name, 'uses'=>'BusinessesController@listByCity']);

      Route::get($city.'/'.(str_plural($category_slug)).'/{services?}', 
                  ['as'=>$name, /*'uses'=>'BusinessesController@listByCity']*/
                      function($services) use($city){
                        return Redirect::to($city.'/salons-and-spas/'.$services);
                      }
                  ]);
      
      $name = 'businesses.list.category.'.$category_slug.'.by.city.and.zone.for.'.$city;
      Route::get($city.'/{subzone}-'.(str_plural($category_slug)), 
                  ['as'=>$name, 'uses'=>'BusinessesController@listByCityAndZone']);

      Route::get($city.'/{subzone}-'.(str_plural($category_slug)).'/{services?}', 
                  ['as'=>$name,
                     function($subzone, $services) use($city){
                        if(is_numeric($subzone)){
                          $subzone = Zone::find($subzone)->slug; 
                        }
                        return Redirect::to($city.'/'.$subzone.'-salons-and-spas/'.$services);
                      }
                  ]);


    endforeach;

    Route::get($city.'/beauty-and-wellness-centers-chain/{chain}', 
                      ['as'=>'businesses.chains.by.city.legacy.append.for.'.$city, 
                        'uses'=>'BusinessesController@listChainsByCity']);

    Route::get($city.'/salons-spas-and-fitness-chain/{chain}', 
                      ['as'=>'businesses.chains.by.city.append.for.'.$city, 
                        'uses'=>'BusinessesController@listChainsByCity']);
    //Route::get($city.'/{slug}', ['as'=>'businesses.view', 'uses'=> 'BusinessesController@slug']);
    Route::get('find/{category-slug}', 
                  ['as'=>'businesses.search.by.category', 
                  'uses'=> 'BusinessesController@category']);
  endforeach;

  Route::resource('businesses', 'BusinessesController');
});

//remember(1800, 'city.route.listings')
$cities = mzk_cities_as_associative_from_json('id', 'slug');

foreach($cities as $city_id => $city):
//foreach(Zone::query()->cities()->get()->lists('slug', 'id')->all() as $city):

  Route::get($city.'/directory', [ 'as'=>'sitemap.for.'.$city, 
                                'uses'=> 'HomeController@sitemapForCity']);

  Route::get($city.'/directory/venues', [ 'as'=>'sitemap.venues.for.'.$city, 
                                'uses'=> 'HomeController@sitemapVenuesForCity']);

  Route::get($city.'/directory/locations', [ 'as'=>'sitemap.locations.for.'.$city, 
                                'uses'=> 'HomeController@sitemapLocationsForCity']);

  Route::get($city.'/{slug}', [ 'as'=>'businesses.view.by.slug.for.'.$city, 
                                'uses'=> 'BusinessesController@slug']);

  Route::get($city.'/{slug}/rate-card', [ 'as'=>'businesses.rates.by.slug.for.'.$city, 
                                          'uses'=> 'BusinessesController@slugRateCard']);

  Route::get($city.'/{slug}/packages', [ 'as'=>'businesses.packages.by.slug.for.'.$city, 
                                          'uses'=> 'BusinessesController@slugPackages']);

  Route::get($city.'/{slug}/photos', ['as'=>'businesses.photos.by.slug.for.'.$city, 
                                      'uses'=> 'BusinessesController@slugPhotos']);

  Route::get($city.'/{slug}/packages', ['as'=>'businesses.packages.by.slug.for.'.$city, 
                                        'uses'=> 'BusinessesController@slugPackages']);

app/Http/Controllers/Administration/Ad_setsController.php
<?php
namespace App\Http\Controllers\Administration;


use  BaseController, View, Config, Validator, Redirect, Input;
use App\Models\User;
use App\Models\App;
use App\Models\Ad;
use App\Models\Campaign;
use App\Models\Ad_set;

use App\Http\Controllers\Controller;


class Ad_setsController extends Controller {

	/**
	 * Ad_set Repository
	 *
	 * @var Ad_set
	 */
	protected $ad_set, $ad;

	public function __construct(Ad_set $ad_set, Ad $ad)
	{
		$this->ad_set = $ad_set;
		$this->ad = $ad;
    $this->layout = 'layouts.admin-crm';
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$ad_sets = $this->ad_set->all();

		//$this->layout = View::make('layouts.admin');
    return View::make('administration.ad_sets.index', compact('ad_sets'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//$this->layout = View::make('layouts.admin');
    return View::make('administration.ad_sets.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		$validation = Validator::make($input, Ad_set::$rules);

		if ($validation->passes())
		{
			$ad_set = $this->ad_set->create($input);
			$ad_set->setCity();
			$ad_set->save();
			
			return Redirect::back();//route('admin.ad_sets.index');
		}

		return Redirect::route('admin.ad_sets.create')
			->withInput()
			->withErrors($validation)
			->with('message', 'There were validation errors.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$ad_set = $this->ad_set->findOrFail($id);

		//$this->layout = View::make('layouts.admin');
    return View::make('administration.ad_sets.show', compact('ad_set'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$adset = $this->ad_set->find($id);

		return View::make('administration.ad_sets.form', compact('adset'));
		////$this->layout = View::make('layouts.admin');
    //$this->layout->content = View::make('administration.ad_sets.edit', compact('ad_set'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$input = array_except(Input::all(), '_method');
		$validation = Validator::make($input, Ad_set::$rules);

		//if($validation->passes())
		{
			$ad_set = $this->ad_set->find($id);
			$ad_set->update($input);

			return Redirect::back();//('admin.ad_sets.show', $id);
		}

		return Redirect::route('admin.ad_sets.edit', $id)
			->withInput()
			->withErrors($validation)
			->with('message', 'There were validation errors.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$this->ad_set->find($id)->delete();
		return Redirect::back();
		//return Redirect::route('admin.ad_sets.index');
	}



	public function getCreateAd($adset_id)
	{
		$adset = Ad_set::find($adset_id);
		$campaign = $adset->campaign;
		//$this->layout = View::make('layouts.admin');
    return View::make('administration.ad_sets.ads.create', compact('adset', 'campaign'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function postCreateAd($adset_id)
	{
		$input = Input::all();
		$validation = Validator::make($input, Ad::$rules);
		$adset = Ad_set::find($adset_id);

		if ($validation->passes())
		{
			$data = Input::except('photo');
			$ad = $this->ad->create($data);
			$ad->saveImage($input['photo']);

			return Redirect::route('admin.campaigns.show', $adset->campaign_id);
		}

		return Redirect::back()
			->withInput()
			->withErrors($validation)
			->with('message', 'There were validation errors.');
	}

	public function getEditAd($ad_id)
	{
		$id = $ad_id;
		$ad = $this->ad->find($id);

		if (is_null($ad))
		{
			return Redirect::route('admin.ads.index');
		}
		$adset = Ad_set::find($ad->ad_set_id);
		$campaign = Campaign::find($adset->campaign_id);

		//$this->layout = View::make('layouts.admin');
    return View::make('administration.ad_sets.ads.edit', compact('ad', 'campaign', 'adset'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function postEditAd($ad_id)
	{
		$id = $ad_id;

		$input = array_except(Input::all(), '_method');
		$validation = Validator::make($input, Ad::$rules);

		if ($validation->passes())
		{
			$data = Input::except('photo', '_method', 'deletablePhotos');
			$ad = $this->ad->find($id);
			$ad->update($data);
			$deletable = Input::get('deletablePhotos');
			if(count($deletable)>0){
				$ad->removeImage();
			}
			if(isset($input['photo'])){
				$ad->saveImage($input['photo']);
			}

			$adset = Ad_set::find($ad->ad_set_id);


			return Redirect::route('admin.campaigns.show', $adset->campaign_id);
		}

		return Redirect::back()
			->withInput()
			->withErrors($validation)
			->with('message', 'There were validation errors.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroyAd($id)
	{
		$this->ad->find($id)->delete();

		return Redirect::back();
	}




}

app/Http/Controllers/Administration/AdminBaseController.php
<?php

namespace App\Http\Controllers\Administration;


use Confide;
use App\Http\Controllers\BaseController as BaseController;
use View;
use Config;
use Validator;
use Redirect;
use Input;

class Controller extends Controller {

	/**
	 * Setup the layout used by the controller.
	 *
	 * @return void
	 */

	function __contruct()
	{
  	$this->setupLayout();
	}

	protected function setupLayout()
	{
		if ( ! is_null($this->layout))
		{
			$this->layout = View::make($this->layout);
		}
	}

}

app/Http/Controllers/Administration/CheckController.php
<?php

namespace App\Http\Controllers\Administration;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class CheckController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update($id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/administration/promotions/create.blade.php
<div class="row">
  <div class="col-md-12">
    <h1>Create Promotion for {{ $business->name }}</h1>
{{ link_to_route('admin.businesses.show', 'Return', array($business->id), array('class' => 'btn btn-info btn-xs')) }}

    @if ($errors->any())
    	<div class="alert alert-danger">
  	    <ul>
          {{ implode('', $errors->all('<li class="error">:message</li>')) }}
        </ul>
    	</div>
    @endif



{{ BootForm::openHorizontal(['sm' => [4, 8], 'lg' => [3, 8] ])
          ->post()
          ->action(
                    route('admin.businesses.create.promotion', array($business->id))
                  )->encodingType('multipart/form-data') }}

   @if (Session::get('error'))
    <div class="alert alert-error alert-danger">
      {{{ is_array(Session::get('error'))?join(',', Session::get('error')):Session::get('error') }}}
    </div>
  @endif
  @if (Session::get('notice'))
    <div class="alert alert-success">
      {{{ is_array(Session::get('notice'))?join(',', Session::get('notice')):Session::get('notice') }}}
    </div>
  @endif
  {{ BootForm::text('Title', 'title')->placeholder('Promotion Title') }}
  {{ BootForm::textarea('Description', 'description')->placeholder('Description') }}
  {{ BootForm::file('Photo', 'artwork') }}
      @if(isset($promotion))
        @if($promotion->artwork)
          <a href="{{ $promotion->artwork->url() }}" class="lightbox"><img src="{{ $promotion->artwork->image->url('thumbnail') }}" class="img-thumbnail" /></a>
          {{ Form::checkbox("deletablePhotos[]", $promotion->artwork->id, false ) }}
          Delete?

        @endif

      @endif

  {{ BootForm::date('Starts', 'starts')->placeholder('starts on')->addClass('dateinput') }}
  {{ BootForm::date('Ends', 'ends')->placeholder('ends on')->addClass('dateinput') }}
  {{ BootForm::select('Promotion Type', 'type', Promotion::$types) }}
  {{ BootForm::select('Status', 'status', Promotion::$statuses) }}
  {{ BootForm::text('Amount', 'amount')->placeholder('Amount Discounted by') }}
  {{ BootForm::select('Discounted As?', 'discounted_as', ['percent', 'amount']) }}

  {{ BootForm::token() }}
  {{ BootForm::submit('Create') }}

{{ BootForm::close() }}

  </div>
</div>
<script type="text/javascript">
$(function(){
  $('.dateinput input').datepicker({ format: "yyyy-mm-dd", autoclose:true });
  $('input.dateinput').datepicker({ dateFormat: "yy-mm-dd", autoclose:true });

})
</script>

resources/views/administration/promotions/edit.blade.php
<div class="row">
  <div class="col-md-12">
    <h1>Edit Promotion for {{ $business->name }}</h1>
{{ link_to_route('admin.businesses.show', 'Return', array($business->id), array('class' => 'btn btn-info btn-xs')) }}

    @if ($errors->any())
        <div class="alert alert-danger">
        <ul>
          {{ implode('', $errors->all('<li class="error">:message</li>')) }}
        </ul>
        </div>
    @endif



{{ BootForm::openHorizontal(['sm' => [4, 8], 'lg' => [3, 8] ])
          ->post()
          ->action(
                    route('admin.businesses.update.promotion', array($business->id, $promotion->id))
                  )->encodingType('multipart/form-data') }}
{{ BootForm::bind($promotion)}}
   @if (Session::get('error'))
    <div class="alert alert-error alert-danger">
      {{{ is_array(Session::get('error'))?join(',', Session::get('error')):Session::get('error') }}}
    </div>
  @endif
  @if (Session::get('notice'))
    <div class="alert alert-success">
      {{{ is_array(Session::get('notice'))?join(',', Session::get('notice')):Session::get('notice') }}}
    </div>
  @endif
  {{ BootForm::text('Title', 'title')->placeholder('Promotion Title') }}
  {{ BootForm::textarea('Description', 'description')->placeholder('Description') }}
  {{ BootForm::file('Photo', 'artwork') }}
      @if(isset($promotion))
        @if($promotion->artwork)
          <a href="{{ $promotion->artwork->url() }}" class="lightbox"><img src="{{ $promotion->artwork->image->url('thumbnail') }}" class="img-thumbnail" /></a>
          {{ Form::checkbox("deletablePhotos[]", $promotion->artwork->id, false ) }}
          Delete?

        @endif

      @endif

  {{ BootForm::date('Starts', 'starts')->placeholder('starts on')->addClass('dateinput') }}
  {{ BootForm::date('Ends', 'ends')->placeholder('ends on')->addClass('dateinput') }}
  {{ BootForm::select('Promotion Type', 'type', Promotion::$types) }}
  {{ BootForm::select('Status', 'status', Promotion::$statuses) }}
  {{ BootForm::text('Amount', 'amount')->placeholder('Amount Discounted by') }}
  {{ BootForm::select('Discounted As?', 'discounted_as', ['percent', 'amount']) }}

  {{ BootForm::token() }}
  {{ BootForm::submit('Create') }}

{{ BootForm::close() }}

  </div>
</div>
<script type="text/javascript">
$(function(){
  $('.dateinput input').datepicker({ format: "yyyy-mm-dd", autoclose:true });
  $('input.dateinput').datepicker({ dateFormat: "yy-mm-dd", autoclose:true });

})
</script>

resources/views/administration/promotions/index.blade.php
<h1>All Promotions</h1>

<p>{{ link_to_route('promotions.create', 'Add New Promotion', null, array('class' => 'btn btn-lg btn-success')) }}</p>

@if ($promotions->count())
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Title</th>
				<th>Description</th>
				<th>Starts</th>
				<th>Ends</th>
				<th>Type</th>
				<th>Business_id</th>
				<th>Status</th>
				<th>Amount</th>
				<th>Discounted_as</th>
				<th>&nbsp;</th>
			</tr>
		</thead>

		<tbody>
			@foreach ($promotions as $promotion)
				<tr>
					<td>{{{ $promotion->title }}}</td>
					<td>{{{ $promotion->description }}}</td>
					<td>{{{ $promotion->starts }}}</td>
					<td>{{{ $promotion->ends }}}</td>
					<td>{{{ $promotion->type }}}</td>
					<td>{{{ $promotion->business_id }}}</td>
					<td>{{{ $promotion->status }}}</td>
					<td>{{{ $promotion->amount }}}</td>
					<td>{{{ $promotion->discounted_as }}}</td>
                    <td>
                        {{ Form::open(array('style' => 'display: inline-block;', 'method' => 'DELETE', 'route' => array('promotions.destroy', $promotion->id))) }}
                            {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                        {{ Form::close() }}
                        {{ link_to_route('promotions.edit', 'Edit', array($promotion->id), array('class' => 'btn btn-info')) }}
                    </td>
				</tr>
			@endforeach
		</tbody>
	</table>
@else
	There are no promotions
@endif

resources/views/administration/promotions/show.blade.php
<h1>Show Promotion</h1>

<p>{{ link_to_route('promotions.index', 'Return to All promotions', null, array('class'=>'btn btn-lg btn-primary')) }}</p>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Title</th>
				<th>Description</th>
				<th>Starts</th>
				<th>Ends</th>
				<th>Type</th>
				<th>Business_id</th>
				<th>Status</th>
				<th>Amount</th>
				<th>Discounted_as</th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td>{{{ $promotion->title }}}</td>
					<td>{{{ $promotion->description }}}</td>
					<td>{{{ $promotion->starts }}}</td>
					<td>{{{ $promotion->ends }}}</td>
					<td>{{{ $promotion->type }}}</td>
					<td>{{{ $promotion->business_id }}}</td>
					<td>{{{ $promotion->status }}}</td>
					<td>{{{ $promotion->amount }}}</td>
					<td>{{{ $promotion->discounted_as }}}</td>
                    <td>
                        {{ Form::open(array('style' => 'display: inline-block;', 'method' => 'DELETE', 'route' => array('promotions.destroy', $promotion->id))) }}
                            {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                        {{ Form::close() }}
                        {{ link_to_route('promotions.edit', 'Edit', array($promotion->id), array('class' => 'btn btn-info')) }}
                    </td>
		</tr>
	</tbody>
</table>