app/Http/routes.php
  Route::post('combo_items/updatable', ['uses'=>'Administration\\Combo_itemsController@updatable', 'as'=>'admin.combo.items.update']);
  Route::post('menu_groups/updatable', ['uses'=>'Administration\\Menu_groupsController@updatable', 'as'=>'admin.menu.groups.update']);
  Route::post('invoice/items/updatable', ['uses'=>'Administration\\InvoicesController@updateInvoiceItem', 'as'=>'admin.invoices.items.update']);
  Route::post('invoice/attach', ['uses'=>'Administration\\InvoicesController@attach', 'as'=>'admin.invoices.attach']);

  Route::post('special_items/updatable', ['uses'=>'Administration\\Service_itemsController@updatable', 'as'=>'admin.special.items.update']);
  Route::post('offers/updatable', ['uses'=>'Administration\\OffersController@updatable', 'as'=>'admin.offers.items.update']);
  Route::post('comments/updatable', ['uses'=>'Administration\\CommentsController@updatable', 'as'=>'admin.comments.updatable']);

  Route::resource('service_items', 'Administration\\Service_itemsController', array('names' => mzk_route_helper('service_items', 'admin')));

  Route::post('photos/upload', ['uses'=>'Administration\\PhotosController@upload', 'as'=>'admin.photos.upload']);

  Route::post('photos/change/type', ['uses'=>'Administration\\PhotosController@changeType', 'as'=>'admin.photos.change.type']);

  Route::resource('posts', 'PostsController');
  Route::resource('posts', 'Administration\\PostsController', 
                          array('names' => mzk_route_helper('posts', 'admin')));

  Route::post('links/{id}/updare', ['uses'=>'Administration\\SelfiesController@updateUrl', 
                                    'as'=>'admin.url.update']);

  Route::resource('selfies', 'Administration\\SelfiesController', 
                          array('names' => mzk_route_helper('selfies', 'admin')));


  Route::get('service_items/list_tags', ['uses'=>'Administration\\Service_itemsController@listTags', 'as'=>'admin.special.items.listTags']);
});


Route::group(array('before' => 'admin.auth', 'prefix'=>'editor' ), function(){
  Route::get('/', 'Administration\\HomeController@editorDashboard');

  Route::get('/published', ['uses'=>'Administration\\PostsController@published', 
                    'as'=>'admin.posts.published']);
  Route::get('/rejects', ['uses'=>'Administration\\PostsController@rejects', 
                    'as'=>'admin.posts.rejects']);
  Route::get('/all', ['uses'=>'Administration\\PostsController@all', 
                    'as'=>'admin.posts.all']);
  Route::get('/pending', ['uses'=>'Administration\\PostsController@pending', 
                    'as'=>'admin.posts.pending']);
  Route::get('/drafts', ['uses'=>'Administration\\PostsController@drafts', 
                    'as'=>'admin.posts.drafts']);

  Route::get('/archives', ['uses'=>'Administration\\PostsController@archives', 
                    'as'=>'admin.posts.archives']);

  Route::get('posts/{id}/archive', ['as'=>'admin.posts.archive', 
                                    'uses'=>'Administration\\PostsController@archive']);

  Route::get('posts/{id}/unarchive', ['as'=>'admin.posts.unarchive', 
                                    'uses'=>'Administration\\PostsController@archive']);

  Route::resource('posts', 'Administration\\PostsController', 
                          array('names' => mzk_route_helper('posts', 'admin')));
});


Route::group(array('before' => 'finance.auth', 'prefix'=>'finance'), function(){
  Route::get('/', ['as'=>'finance.dashboard', 'uses'=>'Administration\\HomeController@financeDashboard']);

  Route::any('payments/{id}/allocate', ['as'=>'admin.payments.allocate', 
                                      'uses'=>'Administration\\PaymentsController@allocate']);
  Route::any('payments/{id}/deallocate', ['as'=>'admin.payments.deallocate', 
                                      'uses'=>'Administration\\PaymentsController@deallocate']);

  Route::any('invoices/{id}/allocate/payments', ['as'=>'admin.invoice.payments.allocate', 
                                      'uses'=>'Administration\\InvoicesController@allocatePaymentsApplicable']);

  Route::any('payment_applicables/{id}/delete', ['as'=>'admin.payment_applicables.delete', 
                                      'uses'=>'Administration\\InvoicesController@deletePaymentApplicables']);



  Route::get('invoices/{id}/pdf', ['as'=>'admin.invoices.pdf', 
                                      'uses'=>'Administration\\InvoicesController@getPdf']);
  Route::post('invoices/save-tax', ['as'=>'admin.invoices.save.tax', 
                                      'uses'=>'Administration\\InvoicesController@saveTax']);


  Route::post('invoices/save-charges', ['as'=>'admin.invoices.save.bounce-charges', 
                                      'uses'=>'Administration\\InvoicesController@saveBounceCharges']);

  Route::get('credit_notes/{id}/pdf', ['as'=>'admin.credit_notes.pdf', 
                                      'uses'=>'Administration\\Credit_notesController@getPdf']);

  Route::get('invoices/search', ['as'=>'admin.invoices.search', 
                                      'uses'=>'Administration\\InvoicesController@getInvoice']);

  Route::get('payments/search', ['as'=>'admin.payments.search', 
                                      'uses'=>'Administration\\PaymentsController@getPayment']);

  Route::any('payments/{id}/recieved-to-deposited', ['as'=>'admin.payments.recieved-to-deposited', 
                      'uses'=>'Administration\\PaymentsController@changeStatusRecievedToDeposited']);

  Route::any('payments/{id}/deposited-to-returned', ['as'=>'admin.payments.deposited-to-returned', 
                      'uses'=>'Administration\\PaymentsController@changeStatusDepositedToReturned']);

  Route::any('payments/{id}/returned-to-deposited', ['as'=>'admin.payments.returned-to-deposited', 
                      'uses'=>'Administration\\PaymentsController@changeStatusReturnedToDeposited']);

  Route::any('payments/{id}/deposited-to-cleared', ['as'=>'admin.payments.deposited-to-cleared', 
                      'uses'=>'Administration\\PaymentsController@changeStatusDepositedToCleared']);

  Route::resource('credit_notes', 'Administration\\Credit_notesController', 
                              array('names' => mzk_route_helper('credit_notes', 'admin')));

  Route::resource('invoices', 'Administration\\InvoicesController', 
                              array('names' => mzk_route_helper('invoices', 'admin')));
  Route::post('credit_notes/updatable', ['uses'=>'Administration\\Credit_notesController@updatable', 'as'=>'admin.credit_notes.updatable']);

  Route::resource('payments', 'Administration\\PaymentsController', 
                              array('names' => mzk_route_helper('payments', 'admin')));
  Route::get('merchants/call-logs/get-businesses', ['as'=>'admin.merchants.call_logs.businesses', 'uses'=>'Administration\\MerchantsController@getOutletsForMerchantInvoiceForm']);

  Route::get('merchants/toggle-leads-access-for-business/{id}', ['as'=>'admin.merchants.toggle_leads_access.businesses', 'uses'=>'Administration\\MerchantsController@toggleLeadsAccessForBusiness']);
  Route::get('merchants/toggle-resumes-access-for-business/{id}', ['as'=>'admin.merchants.toggle_resumes_access.businesses', 'uses'=>'Administration\\MerchantsController@toggleResumesAccessForBusiness']);
  Route::get('merchants/toggle-debug-for-business/{id}', ['as'=>'admin.merchants.toggle_debug.businesses', 'uses'=>'Administration\\BusinessesController@toggleDebug']);

  Route::get('invoices/ppl/create', ['as'=>'admin.invoices.ppl.create', 'uses'=>'Administration\\InvoicesController@createPPLForm']);
  Route::post('invoices/ppl/store', ['as'=>'admin.invoices.ppl.store', 'uses'=>'Administration\\InvoicesController@storePPL']);
  Route::post('invoices/ppl/update', ['as'=>'admin.invoices.ppl.update', 'uses'=>'Administration\\InvoicesController@updatePPL']);
  Route::get('invoices/get/call-logs', ['as'=>'admin.invoices.get.call_logs', 'uses'=>'Administration\\Call_logsController@getCallLogsForInvoiceForm']);
  Route::get('reports', ['as'=>'finance.reports', 'uses'=>'Administration\\FinanceController@reports']);
  Route::get('reports_old', ['as'=>'finance.reports', 'uses'=>'Administration\\FinanceController@reports_old']);
  Route::get('billings/user', ['as'=>'finance.billings.users', 'uses'=>'Administration\\FinanceController@billingsByPOC']);
  Route::get('billings/city', ['as'=>'finance.billings.cities', 'uses'=>'Administration\\FinanceController@billingsByCity']);
  Route::get('expenses',      ['as'=>'finance.expenses', 'uses'=>'Administration\\FinanceController@expenses']);
  Route::get('expenses/create', ['as'=>'finance.expenses.create', 'uses'=>'Administration\\FinanceController@getCreateExpense']);
  Route::post('expenses/create', ['as'=>'finance.expenses.store', 'uses'=>'Administration\\FinanceController@postCreateExpense']);
  Route::get('expenses/{id}/edit', ['as'=>'finance.expenses.edit', 'uses'=>'Administration\\FinanceController@getEditExpense']);
  Route::post('expenses/{id}/update', ['as'=>'finance.expenses.update', 'uses'=>'Administration\\FinanceController@postUpdateExpense']);
  Route::get('expenses/{id}/destroy', ['as'=>'finance.expenses.delete', 'uses'=>'Administration\\FinanceController@destroyExpense']);

});

Route::group(array('before' => 'crm.auth', 'prefix'=>'crm'), function(){
  Route::get('/', ['as'=>'crm.dashboard', 'uses'=>'Administration\\HomeController@crmDashboard']);
  Route::get('businesses/search', ['as'=>'crm.businesses.search', 'uses'=>'Administration\\BusinessesController@search']);

  Route::resource('business_zones', 'Administration\\Business_zonesController', array('names' => mzk_route_helper('business_zones', 'admin')));  

  Route::get('leads/import', ['as'=>'crm.leads.get.import', 'uses'=>'Administration\\LeadsController@getImport']);
  Route::post('leads/importing', ['as'=>'crm.leads.post.import', 'uses'=>'Administration\\LeadsController@postImport']);

app/Models/Finance.php
<?php
namespace App\Models;

use LaravelArdent\Ardent\Ardent;
use Auth;
use App\Models\Zone;

class Finance extends Ardent {
	protected $guarded = array();

  public static $fields = array('desc','type','amount','currency',
                                'usd_amount','user_id','dated','city_id');
  const DEBIT = 'debit';
  const CREDIT = 'credit';

	public static $rules = array(
		'type' => 'required',
		'amount' => 'required',
		'currency' => 'required'
	);

  public function afterCreate(){
    $this->assignNumber();
    $this->save();
  }

  public function assignNumber(){
    $this->title = $this->generateNumber();
  }

  public function city(){
    return $this->belongsTo('App\Models\Zone', 'city_id');
  }

  public function generateNumber(){
    $num = ['EX'];
    $num[] = $this->city_id;
    $num[] = date('my');
    $num[] = str_pad($this->id, 10, "0", STR_PAD_LEFT);
    return join('/', $num);
  }
  public function scopeOnlyExpenses($query){
    return $query->onlyCredits();
  }

  public function scopeOnlyCredits($query){
    return $query->where('type', '=', Finance::CREDIT);
  }


  public function scopeByMonthYear($query, $month = false, $year = false){

    // get offers which have expired in the last 7 days
    $month = $month ? $month : date('m');
    $year = $year ? $year : date('Y');

    $start_of = \Carbon\Carbon::createFromDate($year, $month, 1);
    $end_of = \Carbon\Carbon::createFromDate($year, $month, date("t", strtotime($start_of)));

    return $query->whereRaw('(dated <= "'.$end_of->toDateString().'" AND dated >= "'.$start_of->toDateString().'")');
  }


  public function scopeByMonthYearRange($query, $start_month = false, $start_year = false, $end_month = false, $end_year = false){

    // get offers which have expired in the last 7 days
    $start_month = $start_month ? $start_month : date('m');
    $start_year = $start_year ? $start_year : date('Y');

    $end_month = $end_month ? $end_month : date('m');
    $end_year = $end_year ? $end_year : date('Y');

    $start_of = \Carbon\Carbon::createFromDate($start_year, $start_month, 1);
    $end_of = \Carbon\Carbon::createFromDate($end_year, $end_month, date("t", strtotime($end_year.'-'.$end_month.'-16')));

    return $query->whereRaw('(dated < "'.$end_of->toDateString().'" AND dated > "'.$start_of->toDateString().'")');
  }


  public function getAmountInrAttribute(){
    if($this->currency == 'INR'){
      return $this->amount;
    }

    if($this->currency == 'AED'){
      return mzk_currency_exchange($this->amount, 'AED', 'INR');
    }

  }

  public function getAmountAedAttribute(){
    if($this->currency == 'AED'){
      return $this->amount;
    }

    if($this->currency == 'INR'){
      return mzk_currency_exchange($this->amount, 'INR', 'AED');
    }

  }

  public function getAmountUsdAttribute(){
    if($this->currency == 'AED'){
      return mzk_currency_exchange($this->amount, 'AED', 'USD');
    }

    if($this->currency == 'INR'){
      return mzk_currency_exchange($this->amount, 'INR', 'USD');
    }

  }

}

resources/views/administration/finance/excel/billings-city.blade.php
        <table class="table table-striped">
          <tr>
            <th>&nbsp;</th>
            <?php $currencies = ['aed', 'usd', 'inr'];?>
            @foreach($result as $period)
              <?php $m = mzk_month_array();?>
              @foreach($currencies as $currency)
                @if($$currency==1)
                  <td>
                    <b>
                      <?php echo $m[$period['month']];?>&nbsp;{{$period['year']}}
                      ({{$currency}})
                    </b>
                  </td>
                @endif
              @endforeach
            @endforeach
          </tr>
          @foreach($all_cities as $city)
            <tr>
              <td>{{ str_replace(' ', '&nbsp;', $city->name) }}</td>
            @foreach($result as $period)

              @if(isset($period['cities'][$city->id]))
                @if($aed==1)
                  <td>{{ number_format($period['cities'][$city->id]['aed'] - $period['cities'][$city->id]['credit_aed'], 2) }}</td>
                @endif
                @if($inr==1)
                  <td>{{ number_format($period['cities'][$city->id]['inr'] - $period['cities'][$city->id]['credit_inr'], 2) }}</td>
                @endif
                @if($usd==1)
                  <td>{{ number_format($period['cities'][$city->id]['usd'] - $period['cities'][$city->id]['credit_usd'], 2) }}</td>
                @endif
              @else
                @if($aed==1)
                  <td>0</td>
                @endif
                @if($inr==1)
                  <td>0</td>
                @endif
                @if($usd==1)
                  <td>0</td>
                @endif
              @endif
          @endforeach
            </tr>
          @endforeach
          <tr>
            <th>TOTAL</th>
            @foreach($result as $period)
              @if($aed==1)
                <th>{{ number_format($period['total_aed']-$period['credit_total_aed'], 2) }}</th>
              @endif
              @if($inr==1)
                <th>{{ number_format($period['total_inr']-$period['credit_total_inr'], 2) }}</th>
              @endif
              @if($usd==1)
                <th>{{ number_format($period['total_usd']-$period['credit_total_usd'], 2) }}</th>
              @endif

            @endforeach

          </tr>
<!--          <tr class="hidden danger">
            <th>CREDIT</th>
            @foreach($result as $period)
              @if($aed==1)
                <th>{{ number_format($period['credit_total_aed'], 2) }}</th>
              @endif
              @if($inr==1)
                <th>{{ number_format($period['credit_total_inr'], 2) }}</th>
              @endif
              @if($usd==1)
                <th>{{ number_format($period['credit_total_usd'], 2) }}</th>
              @endif
            @endforeach

          </tr>-->
          <tr class="warning">
            <th>EXPENSES</th>
            @foreach($result as $period)
              @if($aed==1)
                <th>{{ number_format($period['expenses_aed'], 2) }}</th>
              @endif
              @if($inr==1)
                <th>{{ number_format($period['expenses_inr'], 2) }}</th>
              @endif
              @if($usd==1)
                <th>{{ number_format($period['expenses_usd'], 2) }}</th>
              @endif
            @endforeach
          </tr>
<!--          <tr>
            <th>FINAL&nbsp;TOTAL</th>
            @foreach($result as $period)

              @if($aed==1)
                <th>{{ number_format(($period['total_aed']- ($period['credit_total_aed'])), 2) }}</th>
              @endif
              @if($inr==1)
                <th>{{ number_format(($period['total_inr']- ($period['credit_total_inr'])), 2) }}</th>
              @endif
              @if($usd==1)
                <th>{{ number_format(($period['total_usd']- ($period['credit_total_usd'])), 2) }}</th>
              @endif
            @endforeach

          </tr>-->
          <tr>
            <th>EBR</th>
            @foreach($result as $period)
              <th>
                @if($period['expenses_aed']==0)
                  {{ number_format( (($period['total_aed'] - $period['credit_total_aed'])/1)*100, 2) }}
                @else
                  {{ number_format( (($period['total_aed'] - $period['credit_total_aed'])/$period['expenses_aed'])*100, 2) }}
                @endif
              </th>
              @if(($aed+$inr+$usd)==2)
                <th></th>
              @endif
              @if(($aed+$inr+$usd)==3)
                <th></th>
              @endif
            @endforeach

          </tr>

        </table>

resources/views/administration/finance/excel/reports.blade.php
  <table class="table table-striped">
    <thead>
      <tr>
        <th>INVOICE DESC</th>
        <th>MERCHANT ID</th>
        <th>MERCHANT NAME</th>
        <th>CITY</th>
        <th>SALES&nbsp;POC</th>
        <th>START&nbsp;DATE</th>
        <th>END&nbsp;DATE</th>
        <th>MONTHLY&nbsp;NO&nbsp;TAX&nbsp;(AED)</th>
        <th>MONTHLY&nbsp;NO&nbsp;TAX&nbsp;(INR)</th>
        <th>MONTHLY&nbsp;NO&nbsp;TAX&nbsp;(USD)</th>
        <th>MONTHLY&nbsp;TAX&nbsp;(AED)</th>
        <th>MONTHLY&nbsp;TAX&nbsp;(INR)</th>
        <th>MONTHLY&nbsp;TAX&nbsp;(USD)</th>
        <th>MONTHLY&nbsp;(AED)</th>
        <th>MONTHLY&nbsp;(INR)</th>
        <th>MONTHLY&nbsp;(USD)</th>
      </tr>
    </thead>
    <tbody>
<?php 
  $income_aed = 0;
  $income_inr = 0;
  $income_usd = 0;

  $credit_aed = 0;
  $credit_inr = 0;
  $credit_usd = 0;

  $total_tax_aed = 0;
  $total_tax_inr = 0;
  $total_tax_usd = 0;


  $income_no_tax_aed = 0;
  $income_no_tax_inr = 0;
  $income_no_tax_usd = 0;
?>
    @foreach($invoices as $invoice)

<?php

  $contrib_income_aed = $invoice->currentMonthContributionAED($current_month, $current_year);
  $contrib_income_inr = $invoice->currentMonthContributionINR($current_month, $current_year);
  $contrib_income_usd = $invoice->currentMonthContributionUSD($current_month, $current_year);

  $contrib_tax_aed = $invoice->currentMonthTaxAED($current_month, $current_year);
  $contrib_tax_inr = $invoice->currentMonthTaxINR($current_month, $current_year);
  $contrib_tax_usd = $invoice->currentMonthTaxUSD($current_month, $current_year);


?>    

      <tr>
        <td>{{ link_to_route('admin.invoices.show', $invoice->title, [$invoice->id]) }}</td>
        <td>
          <a href="{{route('admin.merchants.show', [$invoice->merchant_id])}}">
            {{ ($invoice->merchant_id) }}
          </a>
        </td>
        <td>
          <a href="{{route('admin.merchants.show', [$invoice->merchant_id])}}">
            {{ ($invoice->merchant->name) }}
          </a>
        </td>
        <td>{{ $invoice->merchant->city_name() }}</td>
        <td>{{ $invoice->poc_name() }}</td>
        <td>{{ mzk_f_date($invoice->start_date) }}</td>
        <td>{{ mzk_f_date($invoice->end_date) }}</td>
        <td>AED {{{ number_format(($contrib_income_aed - $contrib_tax_aed), 2) }}}</td>
        <td>INR {{{ number_format(($contrib_income_inr - $contrib_tax_inr), 2) }}}</td>
        <td>USD {{{ number_format(($contrib_income_usd - $contrib_tax_usd), 2) }}}</td>

        <td>AED {{{ number_format($contrib_tax_aed, 2) }}}</td>
        <td>INR {{{ number_format($contrib_tax_inr, 2) }}}</td>
        <td>USD {{{ number_format($contrib_tax_usd, 2) }}}</td>

        <td>AED {{{ number_format($contrib_income_aed, 2) }}}</td>
        <td>INR {{{ number_format($contrib_income_inr, 2) }}}</td>
        <td>USD {{{ number_format($contrib_income_usd, 2) }}}</td>
      </tr>
      <?php 
      $income_aed += $contrib_income_aed; //$invoice->currentMonthContributionAED($current_month, $current_year);
      $income_inr += $contrib_income_inr; //$invoice->currentMonthContributionINR($current_month, $current_year);
      $income_usd += $contrib_income_usd; //$invoice->currentMonthContributionUSD($current_month, $current_year);

      $income_no_tax_aed += $contrib_income_aed; //$invoice->currentMonthContributionAED($current_month, $current_year);
      $income_no_tax_inr += $contrib_income_inr; //$invoice->currentMonthContributionINR($current_month, $current_year);
      $income_no_tax_usd += $contrib_income_usd; //$invoice->currentMonthContributionUSD($current_month, $current_year);

      $income_no_tax_aed -= $contrib_tax_aed; //$invoice->currentMonthContributionAED($current_month, $current_year);
      $income_no_tax_inr -= $contrib_tax_inr; //$invoice->currentMonthContributionINR($current_month, $current_year);
      $income_no_tax_usd -= $contrib_tax_usd; //$invoice->currentMonthContributionUSD($current_month, $current_year);
      
      $total_tax_aed += $contrib_tax_aed; //$invoice->currentMonthContributionAED($current_month, $current_year);
      $total_tax_inr += $contrib_tax_inr; //$invoice->currentMonthContributionINR($current_month, $current_year);
      $total_tax_usd += $contrib_tax_usd; //$invoice->currentMonthContributionUSD($current_month, $current_year);

      ?>        
    @endforeach
    @foreach($credit_notes as $credit_note)
    <?php 

      $credit_current_aed = $credit_note->currentMonthContributionAED($current_month, $current_year);
    
      $credit_current_inr = $credit_note->currentMonthContributionINR($current_month, $current_year);
      $credit_current_usd = $credit_note->currentMonthContributionUSD($current_month, $current_year);
    ?>
      <tr class="danger">

        <td>{{ $credit_note->id }}</td>
        <td>
          <a href="{{ route('admin.credit_notes.pdf', array($credit_note->id)) }}" class=" ">
            {{ $credit_note->title }}
          </a>
        </td>
        <td></td>
        <td><a href="{{route('admin.merchants.show', [$invoice->merchant_id])}}">{{ ($credit_note->invoice->merchant->name)}}</a></td>
        <td>{{ $credit_note->invoice->merchant->city_name() }}</td>
        <td></td>
        <td></td>
        <td></td>
        <td>AED {{{ number_format($credit_current_aed, 2) }}}</td>
        <td>INR {{{ number_format($credit_current_inr, 2) }}}</td>
        <td>USD {{{ number_format($credit_current_usd, 2) }}}</td>
      </tr>
      <?php 
      $credit_aed += $credit_current_aed;
      $credit_inr += $credit_current_inr;
      $credit_usd += $credit_current_usd;

      ?>
    @endforeach

      <tr>
        <td colspan="7" >
          <b>GROSS INCOME</b>
        </td>
        <td>
          <b>AED {{ number_format($income_no_tax_aed, 2) }}</b>
        </td>
        <td>
          <b>INR {{ number_format($income_no_tax_inr, 2) }}</b>
        </td>
        <td>
          <b>USD {{ number_format($income_no_tax_usd, 2) }}</b>
        </td>
        <td>
          <b>AED {{ number_format($total_tax_aed, 2) }}</b>
        </td>
        <td>
          <b>INR {{ number_format($total_tax_inr, 2) }}</b>
        </td>
        <td>
          <b>USD {{ number_format($total_tax_usd, 2) }}</b>
        </td>
        <td>
          <b>AED {{ number_format($income_aed, 2) }}</b>
        </td>
        <td>
          <b>INR {{ number_format($income_inr, 2) }}</b>
        </td>
        <td>
          <b>USD {{ number_format($income_usd, 2) }}</b>
        </td>
      </tr>
      <tr class="danger">
        <td  colspan="7" >
          <b>CREDIT RAISED</b>
        </td>
        <td>
          <b>AED {{ number_format($credit_aed, 2) }}</b>
        </td>
        <td>
          <b>INR {{ number_format($credit_inr, 2) }}</b>
        </td>
        <td>
          <b>USD {{ number_format($credit_usd, 2) }}</b>
        </td>
        <td colspan="6"></td>


      </tr>
<?php 

$expenses_usd = 0;
$expenses_inr = 0;
$expenses_aed = 0;


foreach($current_month_expenses as $expense){
  $expenses_usd  += $expense->amount_usd;
  $expenses_inr  += $expense->amount_inr;
  $expenses_aed  += $expense->amount_aed;
}


?>

      <tr>
        <td colspan="7" >
          <b>NET INCOME</b>
        </td>
        <td colspan="6"></td>
        <td>
          <b>AED {{ number_format($income_aed - ($credit_aed), 2) }}</b>
        </td>
        <td>
          <b>INR {{ number_format($income_inr - ($credit_inr), 2) }}</b>
        </td>
        <td>
          <b>USD {{ number_format($income_usd - ($credit_usd), 2) }}</b>
        </td>

      </tr>
      <tr >
        <td colspan="15" ></td></tr>

      <tr class="warning">
        <td colspan="7" >
          <b>EXPENSES</b>
        </td>
        <td colspan="6"></td>
        <td>
          <b>AED {{ number_format($expenses_aed, 2) }}</b>
        </td>
        <td>
          <b>INR {{ number_format($expenses_inr, 2) }}</b>
        </td>
        <td>
          <b>USD {{ number_format($expenses_usd, 2) }}</b>
        </td>
      </tr>
      <tr>
        <td colspan="9" >
          <b>EBR</b>
        </td>
        <td colspan="6"></td>
        <td>
          @if($expenses_aed==0)
            <b>{{ number_format(($income_aed - ($credit_aed)/1)*100, 2) }}</b>
          @else
            <b>{{ number_format(($income_aed - ($credit_aed)/$expenses_aed)*100, 2) }}</b>
          @endif
        </td>                
      </tr>
    </tbody>
  </table>
  